"""
Ephemeral per-run filesystem sandbox for agent tool operations.

Provides a sandboxed directory where agents can store and access files
(e.g., downloaded from Drive, generated by MCP servers, attached to emails).
Cleaned up automatically after the run completes.
"""

import mimetypes
import shutil
import uuid
from pathlib import Path


class Sandbox:
    """Sandboxed filesystem for a single agent run."""

    def __init__(self, run_id: str | None = None):
        self.run_id = run_id or uuid.uuid4().hex[:12]
        self.root = Path(f"/tmp/promaia/{self.run_id}")
        self.root.mkdir(parents=True, exist_ok=True)

    def resolve(self, relative_path: str) -> Path:
        """Resolve a relative path to an absolute sandbox path.

        Raises ValueError if the path escapes the sandbox (via '..',
        absolute paths, or symlinks).
        """
        if not relative_path:
            raise ValueError("Empty path")
        # Reject absolute paths before resolving
        if relative_path.startswith("/"):
            raise ValueError(f"Absolute paths not allowed: {relative_path}")

        resolved = (self.root / relative_path).resolve()
        if not resolved.is_relative_to(self.root.resolve()):
            raise ValueError(f"Path escapes sandbox: {relative_path}")
        return resolved

    def list_files(self) -> list[dict]:
        """List all files in the sandbox with metadata."""
        files = []
        for p in sorted(self.root.iterdir()):
            if p.is_file():
                mime, _ = mimetypes.guess_type(str(p))
                files.append({
                    "path": p.name,
                    "size_bytes": p.stat().st_size,
                    "mime_type": mime or "application/octet-stream",
                })
        return files

    def cleanup(self):
        """Remove the sandbox directory and all contents."""
        shutil.rmtree(self.root, ignore_errors=True)

    def __repr__(self) -> str:
        return f"Sandbox(run_id={self.run_id!r}, root={self.root!r})"
