"""
.env file writer that preserves comments, blank lines, and existing values.

All runtime state (`.env`, `promaia.config.json`, `data/`) lives in a data
directory resolved by `get_data_dir()`:

  1. PROMAIA_DATA_DIR env var  (set by docker-compose or user)
  2. {project_root}/maia-data/ (auto-detected if the directory exists)
  3. {project_root}/           (legacy fallback)
"""
import os
import re
import shutil
from pathlib import Path
from typing import List, Optional, Tuple

from promaia.config.paths import get_project_root


def get_data_dir() -> Path:
    """
    Resolve the Promaia data directory.

    Lookup order:
      1. PROMAIA_DATA_DIR env var (absolute or relative to project root)
      2. {project_root}/maia-data/  if it exists
      3. {project_root}/            legacy fallback
    """
    global _guard_suppressed
    _guard_suppressed = True
    override = os.environ.get("PROMAIA_DATA_DIR")
    _guard_suppressed = False
    if override:
        p = Path(override)
        return p if p.is_absolute() else Path(get_project_root()) / p

    project_root = Path(get_project_root())
    maia_data = project_root / "maia-data"
    if maia_data.is_dir():
        return maia_data

    return project_root


def get_prompts_dir() -> Path:
    """Get path to the synced prompts directory inside the data directory."""
    return get_data_dir() / "data" / "md" / "prompts"


def get_env_path() -> Path:
    """Get path to .env file inside the data directory."""
    return get_data_dir() / ".env"


def get_env_example_path() -> Path:
    """Get path to .env.example in project root (always committed, never moves)."""
    return Path(get_project_root()) / ".env.example"


def get_config_path() -> Path:
    """Get path to promaia.config.json inside the data directory."""
    return get_data_dir() / "promaia.config.json"


def get_config_template_path() -> Path:
    """Get path to promaia.config.template.json in project root."""
    return Path(get_project_root()) / "promaia.config.template.json"


def get_db_path() -> Path:
    """Get path to hybrid_metadata.db inside the data directory."""
    return get_data_dir() / "data" / "hybrid_metadata.db"


def get_conversations_db_path() -> Path:
    """Get path to conversations.db inside the data directory."""
    return get_data_dir() / "data" / "conversations.db"


def get_data_subdir() -> Path:
    """Get path to the data/ subdirectory (md/, json/, etc.)."""
    return get_data_dir() / "data"


def get_logs_dir() -> Path:
    """Get path to the logs/ subdirectory inside the data directory."""
    return get_data_dir() / "logs"


def get_cache_dir() -> Path:
    """Get path to the cache/ subdirectory inside the data directory."""
    return get_data_dir() / "cache"


def get_agent_prompts_dir() -> Path:
    """Get path to the agent_prompts/ subdirectory inside the data directory."""
    return get_data_dir() / "agent_prompts"


def get_sync_config_path() -> Path:
    """Get path to sync_config.json inside the data directory."""
    return get_data_dir() / "sync_config.json"


def ensure_env_file() -> Path:
    """
    Ensure .env exists in the data dir. If not, copy from .env.example.
    Creates parent directories if needed.
    Returns path to .env file.
    """
    env_path = get_env_path()
    if not env_path.exists():
        env_path.parent.mkdir(parents=True, exist_ok=True)
        example_path = get_env_example_path()
        if example_path.exists():
            shutil.copy2(example_path, env_path)
        else:
            env_path.write_text(
                "# Promaia Environment Variables\n"
                "# Generated by maia setup\n\n"
                "ANTHROPIC_API_KEY=\n"
                "OPENAI_API_KEY=\n"
                "GOOGLE_API_KEY=\n"
                "MAIA_DEBUG=0\n",
                encoding="utf-8",
            )
    return env_path


def ensure_default_prompts():
    """Copy missing default prompt files into the prompts directory.

    Checks each file in promaia/default_prompts/ and copies it to the
    user's prompts dir if it doesn't already exist.  Never overwrites
    existing files — user customizations are always preserved.
    """
    prompts_dir = get_prompts_dir()
    defaults_dir = Path(__file__).resolve().parent.parent / "default_prompts"

    if not defaults_dir.is_dir():
        return

    prompts_dir.mkdir(parents=True, exist_ok=True)

    import logging
    logger = logging.getLogger(__name__)

    for src in defaults_dir.iterdir():
        if not src.is_file():
            continue
        dest = prompts_dir / src.name
        if not dest.exists():
            shutil.copy2(src, dest)
            logger.info(f"Copied default prompt: {src.name}")


def parse_env_file(path: Path) -> List[Tuple[Optional[str], str]]:
    """
    Parse .env file into a list of (key, raw_line) tuples.

    For comment/blank lines, key is None.
    For KEY=value lines, key is the variable name.
    Preserves exact file structure for round-trip editing.
    """
    lines = []
    if not path.exists():
        return lines

    content = path.read_text(encoding="utf-8")
    for raw_line in content.splitlines():
        stripped = raw_line.strip()

        if not stripped or stripped.startswith("#"):
            lines.append((None, raw_line))
            continue

        match = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\s*=", raw_line)
        if match:
            lines.append((match.group(1), raw_line))
        else:
            lines.append((None, raw_line))

    return lines


def read_env_value(key: str, path: Path = None) -> Optional[str]:
    """Read a single value from .env file. Returns None if key is missing or empty."""
    if path is None:
        path = get_env_path()

    lines = parse_env_file(path)
    for line_key, raw_line in lines:
        if line_key == key:
            _, _, value = raw_line.partition("=")
            value = value.strip().strip("'\"")
            return value if value else None
    return None


def update_env_value(key: str, value: str, path: Path = None) -> None:
    """
    Update a single key in .env file, preserving everything else.

    If key exists: replaces its line.
    If key doesn't exist: appends at end of file.
    """
    if path is None:
        path = ensure_env_file()

    lines = parse_env_file(path)

    found = False
    new_lines = []
    for line_key, raw_line in lines:
        if line_key == key:
            new_lines.append((key, f"{key}={value}"))
            found = True
        else:
            new_lines.append((line_key, raw_line))

    if not found:
        if new_lines and new_lines[-1][1].strip():
            new_lines.append((None, ""))
        new_lines.append((key, f"{key}={value}"))

    output = "\n".join(raw_line for _, raw_line in new_lines) + "\n"
    path.write_text(output, encoding="utf-8")


# ---------------------------------------------------------------------------
# Guard: warn when code outside this module reads path env vars directly
# ---------------------------------------------------------------------------
_GUARDED_KEYS = frozenset({"PROMAIA_DATA_DIR", "PROMAIA_PROJECT_ROOT"})
_guard_installed = False
_guard_suppressed = False


def _install_path_env_guard() -> None:
    """Monkey-patch os.environ.get and os.getenv to warn on direct reads of
    path env vars.

    Only the helpers in this module should read these.  Everyone else
    should call get_data_dir() / get_project_root() etc.
    """
    global _guard_installed
    if _guard_installed:
        return
    _guard_installed = True

    import warnings

    _orig_env_get = os.environ.get
    _orig_getenv = os.getenv

    def _guarded_env_get(key, *args, **kwargs):
        if key in _GUARDED_KEYS and not _guard_suppressed:
            warnings.warn(
                f"Direct os.environ.get({key!r}) — use get_data_dir() or "
                f"get_project_root() from promaia.utils.env_writer instead.",
                stacklevel=2,
            )
        return _orig_env_get(key, *args, **kwargs)

    def _guarded_getenv(key, *args, **kwargs):
        global _guard_suppressed
        if key in _GUARDED_KEYS and not _guard_suppressed:
            warnings.warn(
                f"Direct os.getenv({key!r}) — use get_data_dir() or "
                f"get_project_root() from promaia.utils.env_writer instead.",
                stacklevel=2,
            )
            # Suppress the nested os.environ.get call that os.getenv makes
            _guard_suppressed = True
            result = _orig_getenv(key, *args, **kwargs)
            _guard_suppressed = False
            return result
        return _orig_getenv(key, *args, **kwargs)

    os.environ.get = _guarded_env_get
    os.getenv = _guarded_getenv


_install_path_env_guard()
